services:
  caddy:
#    build:
#      context: .
#      args:
#        - S6_ARCH=${S6_ARCH:-x86_64}
#        - S6_VER=${S6_VER:-3.2.2.0}
#        - CADDY=${CADDY:-caddy:alpine}
    image: ghcr:rchenvt/caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./read/Caddyfile:/etc/caddy/Caddyfile
      - ./log/caddy:/var/log/caddy
      - ./read/lldap_config.toml:/data/lldap/lldap_config.toml
      - ./read/configuration.yml:/config/authelia/configuration.yml
      - ./config:/config
      - ./data:/data
    environment:
      - DOMAINNAME=${DOMAINNAME}
      - TZ=$TZ
      # Caddy
#      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
#      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      # Lldap
      - LLDAP_LDAP_BASE_DN=$LLDAP_LDAP_BASE_DN
      - LLDAP_LDAP_USER_DN=$LLDAP_LDAP_USER_DN
      - LLDAP_LDAP_USER_PASS=$LLDAP_LDAP_USER_PASS
      # Silent lldap session logs
      - RUST_LOG=lldap=warn,warp=warn,hyper=warn,sqlx=warn
      # Authelia
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD=$LLDAP_LDAP_USER_PASS
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN=$LLDAP_LDAP_BASE_DN
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER=uid=${LLDAP_LDAP_USER_DN},ou=people,${LLDAP_LDAP_BASE_DN}
#      - X_AUTHELIA_CONFIG_FILTERS=template
      # Inbucket
      - INBUCKET_LOGLEVEL=error
      # Filebrowser
      - FB_NOAUTH=true
      - 
    restart: unless-stopped
#    networks:
#      - caddy
