#!/command/with-contenv sh
echo "[init-lldap] Preparing LLDAP env..."
mkdir -p /data/lldap
# Fix permissions like the original script
#find /app/lldap \! -user appuser -exec chown appuser:appuser '{}' +
#find /data/lldap \! -user appuser -exec chown appuser:appuser '{}' +
if [ ! -f "/data/lldap/lldap_config.toml" ]; then
    cp -a /app/lldap/lldap_config.docker_template.toml /data/lldap/lldap_config.toml
fi
chown -R appuser:appuser /app /data/lldap
