#!/command/with-contenv sh
echo "[init-caddy] Preparing Caddy folders..."
mkdir -p /etc/caddy /data/caddy /config/caddy /var/log/caddy
if [ ! -f /var/log/caddy/caddy.log ]; then
    touch /var/log/caddy/caddy.log
fi
if [ ! -f /var/log/caddy/access.log ]; then
    touch /var/log/caddy/access.log
fi
chown -R appuser:appuser /data/caddy /config/caddy /var/log/caddy
