#!/command/with-contenv sh

echo "[authelia] Waiting for LLDAP to be ready on localhost:3890..."
# Loop until port 3890 is responsive
while ! nc -z 127.0.0.1 3890 || ! nc -z 127.0.0.1 2500; do   
  sleep 1
done

echo "[authelia] LLDAP and INBUCKET are up, starting Authelia..."
exec s6-setuidgid appuser authelia --config /config/authelia/configuration.yml
