#!/command/with-contenv sh
# Dynamically remap the placeholder user to the runtime PUID/PGID

# Update Group GID
if [ ! -z "$PGID" ] && [ "$(id -g appuser)" != "$PGID" ]; then
    echo "[init-permissions] Remapping appuser to GID $PGID"
    sed -i "s/^appuser:x:[0-9]*:/appuser:x:$PGID:/" /etc/group
fi

# Update User UID
if [ ! -z "$PUID" ] && [ "$(id -u appuser)" != "$PUID" ]; then
    echo "[init-permissions] Remapping appuser to UID $PUID"
    sed -i "s/^appuser:x:[0-9]*:[0-9]*:/appuser:x:$PUID:$PGID:/" /etc/passwd
fi

chown appuser:appuser /data /config
